server:
  port: 8888

spring:
  application:
    name: order-consumer

  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    connect-timeout: 1000
    jedis:
      pool:
        #          最大可用连接数（负数表示无限）
        max-active: 8
        #          空闲连接数（负数表示无限）
        max-idle: 8
        min-idle: 0
        #          从连接池获取连接最大等待时间（负数表示无限，单位ms）
        max-wait: -1

eureka:
  client:
    #    默认为true：自动注册到 注册中心
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/