# 应用名称
spring:
  application:
    name: redis-exercise

  #    spring.redis.host=127.0.0.1
  #    spring.redis.port=6379
  #    #客户端超时
  #    spring.redis.timeout=10000
  #    #最大连接数
  #    spring.redis.lettuce.pool.max-active=20
  #    #最小空闲
  #    spring.redis.lettuce.pool.min-idle=5
  #    #连接超时
  #    spring.redis.lettuce.pool.max-wait=5000ms
  #    #最大空闲
  #    spring.redis.lettuce.pool.max-idle=20
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    lettuce:
      pool:
        max-active: 10
        min-idle: 5
        max-wait: 5000
        max-idle: 20



